#!/bin/bash
# =============================================================================
# MacBridge — Workspace Setup (the "prepared studio")
# =============================================================================
# Configures the auto-arranged workspace so a first login feels like walking
# into a studio that was prepared before you arrived (ONBOARDING_ENVIRONMENT
# _STRATEGY.md). Runs once when building the golden image.
#
# It installs:
#   1. A LaunchAgent that, on GUI login, opens Terminal + boots the Simulator.
#   2. A readiness hook in ~/.zprofile so every login shell (Terminal window or
#      SSH session) greets the user with the MacBridge Ready screen.
#
# Idempotent. macOS only. Never touches the network or installs tools.
#
# Usage:
#   bash workspace-setup.sh                 # install (default device auto-picked)
#   bash workspace-setup.sh --device "iPhone 15"
#   bash workspace-setup.sh --dry-run       # show what would change
#   bash workspace-setup.sh --uninstall     # remove the workspace configuration
# =============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRY_RUN=false
UNINSTALL=false
DEVICE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run) DRY_RUN=true; shift ;;
        --uninstall) UNINSTALL=true; shift ;;
        --device) DEVICE="${2:-}"; shift 2 ;;
        --help|-h)
            echo "Usage: bash workspace-setup.sh [--device NAME] [--dry-run] [--uninstall]"
            exit 0
            ;;
        *) shift ;;
    esac
done

AGENT_LABEL="app.macbridge.workspace"
PLIST="$HOME/Library/LaunchAgents/${AGENT_LABEL}.plist"
LOGIN_SCRIPT="$HOME/.macbridge/workspace-login.sh"
ZPROFILE="$HOME/.zprofile"
MARK_BEGIN="# >>> macbridge readiness >>>"
MARK_END="# <<< macbridge readiness <<<"

say() { echo "  $*"; }
act() {
    # Run a command, or just print it under --dry-run.
    if [ "$DRY_RUN" = true ]; then
        echo "  [dry-run] $*"
    else
        eval "$*"
    fi
}

if [ "$(uname -s)" != "Darwin" ] && [ "$DRY_RUN" = false ]; then
    echo "workspace-setup: this configures macOS login behaviour and only runs on macOS." >&2
    echo "Use --dry-run to preview the actions on another platform." >&2
    exit 1
fi

# ── Uninstall ───────────────────────────────────────────────────────────────
if [ "$UNINSTALL" = true ]; then
    echo ""
    echo "MacBridge Workspace — uninstall"
    act "launchctl unload '$PLIST' 2>/dev/null || true"
    act "rm -f '$PLIST'"
    act "rm -f '$LOGIN_SCRIPT'"
    # Strip the readiness block from ~/.zprofile
    if [ -f "$ZPROFILE" ] && grep -q "$MARK_BEGIN" "$ZPROFILE" 2>/dev/null; then
        act "sed -i.bak '/$MARK_BEGIN/,/$MARK_END/d' '$ZPROFILE'"
    fi
    say "Workspace configuration removed."
    echo ""
    exit 0
fi

echo ""
echo "MacBridge Workspace — setup"
echo "==========================="
echo ""

# ── 1. Login launcher script (opens Terminal + boots a Simulator) ───────────
# The device is resolved at login time so it survives golden-image rebuilds.
DEVICE_EXPR='${DEVICE_OVERRIDE:-$(xcrun simctl list devices available 2>/dev/null | grep -oE "iPhone[^(]*" | head -1 | sed "s/[[:space:]]*$//")}'

say "Writing login launcher: $LOGIN_SCRIPT"
if [ "$DRY_RUN" = false ]; then
    mkdir -p "$(dirname "$LOGIN_SCRIPT")"
    cat > "$LOGIN_SCRIPT" <<LOGIN
#!/bin/bash
# Auto-generated by workspace-setup.sh. Opens the prepared studio on login.
DEVICE_OVERRIDE="${DEVICE}"
DEVICE_NAME="$DEVICE_EXPR"

# Open a Terminal window — its login shell renders the readiness screen.
open -a "Terminal" 2>/dev/null || true

# Boot the Simulator to a real device so it is already on screen.
if [ -n "\$DEVICE_NAME" ]; then
    xcrun simctl boot "\$DEVICE_NAME" 2>/dev/null || true
fi
open -a "Simulator" 2>/dev/null || true
LOGIN
    chmod +x "$LOGIN_SCRIPT"
else
    echo "  [dry-run] would write $LOGIN_SCRIPT (opens Terminal + boots Simulator device: ${DEVICE:-auto})"
fi

# ── 2. LaunchAgent that runs the launcher at GUI login ──────────────────────
say "Installing LaunchAgent: $PLIST"
if [ "$DRY_RUN" = false ]; then
    mkdir -p "$(dirname "$PLIST")"
    cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${AGENT_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${LOGIN_SCRIPT}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
PLISTEOF
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load "$PLIST" 2>/dev/null || true
else
    echo "  [dry-run] would install LaunchAgent ${AGENT_LABEL} (RunAtLoad -> ${LOGIN_SCRIPT})"
fi

# ── 3. Readiness hook in ~/.zprofile (login shells greet the user) ──────────
say "Adding readiness hook to $ZPROFILE"
READINESS_BLOCK="$(cat <<HOOK
$MARK_BEGIN
# Show the MacBridge Ready screen once per login shell (Terminal / SSH).
if [ -z "\${MACBRIDGE_READINESS_SHOWN:-}" ] && [ -t 1 ] && [ -f "${SCRIPT_DIR}/readiness.sh" ]; then
    export MACBRIDGE_READINESS_SHOWN=1
    bash "${SCRIPT_DIR}/readiness.sh" --quick || true
fi
$MARK_END
HOOK
)"

if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would append readiness block to $ZPROFILE:"
    printf '%s\n' "$READINESS_BLOCK" | sed 's/^/      /'
elif grep -q "$MARK_BEGIN" "$ZPROFILE" 2>/dev/null; then
    say "Readiness hook already present — leaving as is."
else
    printf '\n%s\n' "$READINESS_BLOCK" >> "$ZPROFILE"
fi

echo ""
if [ "$DRY_RUN" = true ]; then
    say "Dry run complete. No changes were made."
else
    say "Workspace configured. On next login: Terminal opens with the readiness"
    say "screen, and the Simulator boots automatically."
fi
echo ""
