// MacBridge license keygen — JavaScript port of internal/license (Go).
//
// MUST stay byte-exact with the Go implementation: keys generated here are
// validated offline by the shipped CLI (`macbridge activate`). Any drift makes
// sold keys invalid. Compatibility is pinned by test-keygen.mjs, whose vectors
// were generated by the Go mbkeygen.
//
// Format: MB-XXXX-XXXX-XXXX-CCCC — three payload groups + an FNV-1a checksum
// group over the payload ("MB-XXXX-XXXX-XXXX"), alphabet without ambiguous
// characters (no I, L, O, U, 0, 1).

export const ALPHABET = "ABCDEFGHJKMNPQRSTVWXYZ23456789";
const GROUP_LEN = 4;
const NUM_GROUPS = 3;
const PREFIX = "MB";

// FNV-1a 32-bit, matching Go's hash/fnv New32a over the payload bytes.
function fnv1a32(str) {
  let hash = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i); // payload is ASCII by construction
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

// checksum derives the 4-char group exactly like Go: repeated mod/div by the
// alphabet length (integer division).
export function checksum(payload) {
  let sum = fnv1a32(payload);
  let out = "";
  for (let i = 0; i < GROUP_LEN; i++) {
    out += ALPHABET[sum % ALPHABET.length];
    sum = Math.floor(sum / ALPHABET.length);
  }
  return out;
}

// generateKey creates a new valid key. `randomBytes` must be a function
// returning a Uint8Array of the requested length (pass crypto.getRandomValues
// semantics; default works in Workers and Node 19+).
export function generateKey(randomBytes = (n) => crypto.getRandomValues(new Uint8Array(n))) {
  const groups = [];
  for (let g = 0; g < NUM_GROUPS; g++) {
    let chars = "";
    while (chars.length < GROUP_LEN) {
      // Rejection sampling for a uniform draw (256 % 30 !== 0).
      const [b] = randomBytes(1);
      if (b < 240) chars += ALPHABET[b % ALPHABET.length];
    }
    groups.push(chars);
  }
  const payload = `${PREFIX}-${groups.join("-")}`;
  return `${payload}-${checksum(payload)}`;
}

export function normalize(key) {
  return String(key ?? "").trim().toUpperCase();
}

// validate mirrors Go's Validate: structural check + checksum match.
// Returns { ok: true } or { ok: false, reason }.
export function validate(key) {
  key = normalize(key);
  const parts = key.split("-");
  if (parts.length !== NUM_GROUPS + 2) {
    return { ok: false, reason: `key must look like ${PREFIX}-XXXX-XXXX-XXXX-XXXX` };
  }
  if (parts[0] !== PREFIX) {
    return { ok: false, reason: `key must start with ${PREFIX}-` };
  }
  for (const group of parts.slice(1)) {
    if (group.length !== GROUP_LEN) {
      return { ok: false, reason: `each group must be ${GROUP_LEN} characters` };
    }
    for (const c of group) {
      if (!ALPHABET.includes(c)) {
        return { ok: false, reason: `invalid character "${c}"` };
      }
    }
  }
  const payload = parts.slice(0, NUM_GROUPS + 1).join("-");
  if (checksum(payload) !== parts[NUM_GROUPS + 1]) {
    return { ok: false, reason: "checksum does not match" };
  }
  return { ok: true };
}
