// Compatibility tests for the JS keygen port.
// Run: node commerce/test-keygen.mjs
//
// The GO_VECTORS below were generated by the Go implementation
// (`go run ./cmd/mbkeygen`) — they pin the two implementations together.
// If this test fails after touching keygen.mjs or internal/license, the
// implementations have drifted and sold keys would stop validating.

import { checksum, generateKey, validate } from "./keygen.mjs";

let failures = 0;
function assert(cond, msg) {
  if (!cond) {
    failures++;
    console.error(`FAIL: ${msg}`);
  }
}

// 1. Keys generated by the Go implementation must validate in JS.
const GO_VECTORS = [
  "MB-JPC6-J79N-78HR-9GEH",
  "MB-WQTN-9DQ6-B253-NRB8",
  "MB-FH8V-STPC-HAF5-ZFS2",
  "MB-A3YB-PG8N-ZBAK-F8VP",
  "MB-QNP3-XE3H-ES6X-9ZCP",
];
for (const key of GO_VECTORS) {
  assert(validate(key).ok, `Go-generated vector rejected: ${key}`);
  // The JS checksum of the payload must reproduce the Go checksum group.
  const payload = key.split("-").slice(0, 4).join("-");
  const expect = key.split("-")[4];
  assert(checksum(payload) === expect, `checksum drift on ${payload}: js=${checksum(payload)} go=${expect}`);
}

// 2. Tampered vectors must be rejected.
const BAD = [
  "",
  "MB-AAAA-BBBB-CCCC-DDDD",              // random checksum
  "XX-JPC6-J79N-78HR-9GEH",              // wrong prefix
  "MB-JPC6-J79N-78HR",                   // missing checksum group
  "MB-JPC6-J79N-78HR-9GEG",              // flipped checksum char
  "MB-JPC6-J79N-78HL-9GEH",              // L not in alphabet
  "mb-jpc6-j79n-78hr-9geh ",             // should PASS after normalize — asserted below
];
for (const key of BAD.slice(0, 6)) {
  assert(!validate(key).ok, `tampered key accepted: "${key}"`);
}
// Normalization: lowercase/whitespace variants of a valid key pass.
assert(validate(BAD[6]).ok, "normalize should accept lowercase+whitespace of a valid key");

// 3. JS-generated keys are structurally valid and unique.
const seen = new Set();
for (let i = 0; i < 200; i++) {
  const key = generateKey();
  assert(validate(key).ok, `JS-generated key invalid: ${key}`);
  assert(!seen.has(key), `duplicate generated key: ${key}`);
  seen.add(key);
}

if (failures) {
  console.error(`${failures} failure(s)`);
  process.exit(1);
}
console.log("keygen compatibility: all tests passed (5 Go vectors, 6 rejections, 200 generated)");
